name: Build scan deploy
on:
  pull_request:
  push:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "test"
        run: |
          echo ${ACTIONS_ID_TOKEN_REQUEST_URL}
